export enum PhaseId {
  WAITING_START = "WAITING_START",
  PREPARE_SELECT_ACTION = "PREPARE_SELECT_ACTION",
  SELECT_ACTION = "SELECT_ACTION",
  PLACE_MARKER = "PLACE_MARKER",
  PLACE_WALL_TILE = "PLACE_WALL_TILE",
  AUCTION_AND_PLACE_OUTLET_TILE = "AUCTION_AND_PLACE_OUTLET_TILE",
  PLACE_WALL_OR_ROAD_TILE = "PLACE_WALL_OR_ROAD_TILE",
  END_GAME = "END_GAME",
}
